# PluginsMinecraft


BROWN_CONGRETE - CONFUSION
BLACK_CONGRETE - BLINDNESS
ORANGE_CONGRETE - FIRE_RESISTANCE
WHITE_CONGRETE - LEVITATION
GRAY_CONGRETE - SLOW
LIGHT_GRAY_CONGRETE - WEAKNESS
RED_CONGRETE - KILL_PlAYER
YELLOW_CONGRETE - HASTE
LIME_CONGRETE - JUMP
GREEN_CONGRETE - HUNGER
CYAN_CONGRETE - WATER_BREATHING
LIGHT_BLUE_CONGRETE - SPEED
PURPLE_CONGRETE - STRENGE
MAGENTA_CONGRETE - HEAL
PINK_CONGRETE - REGEN
GLOWSTONE - GLOWING
SCULK - NIGHT_VISION
LIME_GLAZED_TERRACOTTA - LUCK
GRAY_GLAZED_TERRACOTTA - BAD_LUCK

